// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDcdaUVXdPZhi8ONaOmgBadPG6kgVUTW2E',
    appId: '1:1068170748256:web:8089313382d73f92bc7e05',
    messagingSenderId: '1068170748256',
    projectId: 'mentalyapb',
    authDomain: 'mentalyapb.firebaseapp.com',
    storageBucket: 'mentalyapb.appspot.com',
    measurementId: 'G-PRY2VXR1HX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCy8RTCxGdZLdwQwFqNIiGnTFxGiP-_Cqw',
    appId: '1:1068170748256:android:1d4f0d9ffa56d2bfbc7e05',
    messagingSenderId: '1068170748256',
    projectId: 'mentalyapb',
    storageBucket: 'mentalyapb.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB8buZIRoxoKMH9mljHEkwlsxFsatCeZXc',
    appId: '1:1068170748256:ios:c06fedab109292d7bc7e05',
    messagingSenderId: '1068170748256',
    projectId: 'mentalyapb',
    storageBucket: 'mentalyapb.appspot.com',
    iosBundleId: 'com.example.apbMentaly',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB8buZIRoxoKMH9mljHEkwlsxFsatCeZXc',
    appId: '1:1068170748256:ios:c06fedab109292d7bc7e05',
    messagingSenderId: '1068170748256',
    projectId: 'mentalyapb',
    storageBucket: 'mentalyapb.appspot.com',
    iosBundleId: 'com.example.apbMentaly',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDcdaUVXdPZhi8ONaOmgBadPG6kgVUTW2E',
    appId: '1:1068170748256:web:b36d9fd36f055ddebc7e05',
    messagingSenderId: '1068170748256',
    projectId: 'mentalyapb',
    authDomain: 'mentalyapb.firebaseapp.com',
    storageBucket: 'mentalyapb.appspot.com',
    measurementId: 'G-SVQVEP8QBV',
  );
}
